version: '3.8'

services:
  postgres-db:
    image: postgres:12.9
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zhenpai
    volumes:
      - pg-zhenpai:/var/lib/postgresql/data

volumes:
  pg-zhenpai:
