name: Build and Deploy to Railway (railway.app)

on:
  push:
    branches:
     - 'master'

jobs:
  migration:
    name: Database Migration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Set up pyway
      run: pip install pyway

    - name: Run pyway
      run: |
        pyway info
        pyway validate
        pyway migrate
      env:
        PYWAY_DATABASE_MIGRATION_DIR: migrations
        PYWAY_TYPE: postgres
        PYWAY_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        PYWAY_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        PYWAY_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        PYWAY_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        PYWAY_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Railway CLI
      run: curl -fsSL cli.new | sh

    - name: Deploy
      run: railway up
      env: 
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        COMMIT_HASH: ${{ vars.GITHUB_SHA }}
        # This should be infered, but let's add it anyways
        RAILWAY_DOCKERFILE_PATH: Dockerfile