name: Build and Deploy to Railway (railway.app)

on:
  push:
    branches:
     - 'master'

jobs:
  migration:
    name: Flyway Migration
    runs-on: ubuntu-latest
    container:
      image: flyway/flyway:9.8.1
      env:
        FLYWAY_URL: jdbc:postgresql://${{ secrets.DATABASE_HOST }}:${{ secrets.DATABASE_PORT }}/${{ secrets.DATABASE_NAME }}
        FLYWAY_USER: ${{ secrets.DATABASE_USERNAME }}
        FLYWAY_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        FLYWAY_LOCATIONS: filesystem:migrations
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Flyway Info
        run: flyway info

      - name: Flyway Migrate
        run: flyway migrate

      - name: Flyway Validate
        run: flyway validate

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: migration

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Railway CLI
      run: curl -fsSL cli.new | sh

    - name: Deploy
      run: railway up
      env: 
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        COMMIT_HASH: ${{ github.sha }}
        # This should be infered, but let's add it anyways
        RAILWAY_DOCKERFILE_PATH: Dockerfile