name: Lint Python

on:
  pull_request:
  push:

jobs:
  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8 . --count --select=E9,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --show-source --statistics